# Dockerfile.worker
FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente
COPY src/ /app/src/

# Ejecutar el worker
CMD ["python", "src/analyzer/worker.py"]
