# Dockerfile.api
FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente
COPY src/ /app/src/

# Exponer el puerto y ejecutar la API
EXPOSE 5000
CMD ["uvicorn", "src.tiktok_scraper.main:app", "--host", "0.0.0.0", "--port", "5000"]
